# Generated by Django 3.2.12 on 2022-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('hidden', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('image', models.FileField(default='./', upload_to='')),
                ('properties', models.ManyToManyField(to='store_test_vst.Property')),
            ],
        ),
    ]
