# Generated by Django 3.2.12 on 2022-04-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_type',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=50),
        ),
    ]
