# Generated by Django 3.2.12 on 2022-04-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0003_item_cost_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'default_related_name': 'property', 'ordering': ('name', 'description', 'id')},
        ),
    ]
