# Generated by Django 3.2.12 on 2022-04-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0005_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'default_related_name': 'properties'},
        ),
    ]
