# Generated by Django 3.2.12 on 2022-04-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0009_alter_property_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='properties',
            new_name='property',
        ),
    ]
