# Generated by Django 3.2.12 on 2022-04-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0010_rename_properties_item_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='property',
            new_name='properties',
        ),
    ]
