# Generated by Django 3.2.12 on 2022-04-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0011_rename_property_item_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
