# Generated by Django 3.2.12 on 2022-04-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0012_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
