# Generated by Django 3.2.12 on 2022-04-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0016_rename_property_techproperty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechProperty',
            new_name='Property',
        ),
    ]
