# Generated by Django 3.2.12 on 2022-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0017_rename_techproperty_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'default_related_name': 'property'},
        ),
    ]
