# Generated by Django 3.2.12 on 2022-04-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_test_vst', '0021_auto_20220412_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characteristic',
            new_name='Property',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'default_related_name': 'property'},
        ),
    ]
